basic:
  name: Insight_MultiModal
  version: 1.0
  task_name: "multimodal_v01_cls24"
  task_type: "multi_label"
  n_gpus: 8                    # 最大8个gpu， 否则会报错
  seed: 666
  id2name: "configs/multimodal_v01_cls24_idx2name_cls24.json"

arch:
  name: "Multi_Fusion_Net"
  resume: ""
  best_model: ""
  use_ema: false
  ema_decay: 0.999
  args:
    text_dim: 768
    video_dim: 1536
    audio_dim: 768
    num_classes: 24

data:
  batch_size: 4
  num_workers: 4
  train_data_path: "/data1/changqing/ZyMultiModal_Data/annotations/v1_cls24/train_cls24.json"
  valid_data_path: "/data1/changqing/ZyMultiModal_Data/annotations/v1_cls24/valid_cls24.json"

runner:
  epochs: 20
  optimizer:
    type: BertAdam
    args:
      lr: 2e-05
      warmup: 0.05
      momentum: 0.9
  lr_scheduler:
    type: StepLR
    args:
      step_size: 10
      gamma: 0.1
  save_dir: "workshop"
  ckpt_dir: "ckpt"
  log_dir: "log"
  save_max: 5
  save_freq:
  valid_interval: 0
  log_interval: 1
  verbosity: 1
  monitor: "valid_gap"
  monitor_mode: "max"
  tensorboardx: true
  resume: ""
  fix_random_seed:

loss: bce_loss
metrics: multi_label
